javax.net.ssl.keyStore=C:/PROSTO_JENbKa/Project/ipr/SSL/client.jks
javax.net.ssl.keyStorePassword=123456
javax.net.ssl.keyStoreType=JKS

javax.net.ssl.trustStore=C:/PROSTO_JENbKa/Project/ipr/SSL/client-truststore.jks
javax.net.ssl.trustStorePassword=123456
javax.net.ssl.trustStoreType=JKS